version: "3.8"

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ../db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=qwer1234
      - MARIADB_DATABASE=tallemalle
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ../backend/.env
    environment:
      - DB_URL=jdbc:mariadb://db:3306/tallemalle
      - DB_USER=root
      - DB_PASS=qwer1234
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
        - VITE_WS_URL=ws://localhost:8080/ws
    ports:
      - "80:80"
    depends_on:
      - backend
